-- Listas personalizadas (RF54), como "Top 10 RPGs". A posição define a ordem.
CREATE TABLE user_lists (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    title VARCHAR(80) NOT NULL,
    description VARCHAR(500),
    visibility VARCHAR(8) NOT NULL DEFAULT 'PUBLIC' CHECK (visibility IN ('PUBLIC', 'PRIVATE')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX user_lists_user_idx ON user_lists (user_id, updated_at DESC);

CREATE TABLE user_list_items (
    list_id BIGINT NOT NULL REFERENCES user_lists (id) ON DELETE CASCADE,
    game_id BIGINT NOT NULL REFERENCES games (id),
    position INTEGER NOT NULL CHECK (position >= 1),
    note VARCHAR(300),
    PRIMARY KEY (list_id, game_id),
    -- Adiado até o commit, para trocar posições numa transação só.
    UNIQUE (list_id, position) DEFERRABLE INITIALLY DEFERRED
);
