CREATE TABLE tb_game (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255),
    game_year INTEGER,
    genre VARCHAR(255),
    platforms VARCHAR(255),
    score DOUBLE PRECISION,
    img_url VARCHAR(255),
    short_description TEXT,
    long_description TEXT
);

CREATE TABLE tb_game_list (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255)
);

CREATE TABLE tb_belonging (
    game_id BIGINT NOT NULL REFERENCES tb_game (id),
    list_id BIGINT NOT NULL REFERENCES tb_game_list (id),
    position INTEGER,
    PRIMARY KEY (game_id, list_id)
);
