DROP TABLE tb_belonging;
DROP TABLE tb_game_list;
DROP TABLE tb_game;

CREATE EXTENSION IF NOT EXISTS pg_trgm;

CREATE TABLE genres (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    igdb_id BIGINT UNIQUE,
    name VARCHAR(100) NOT NULL,
    slug VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE platforms (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    igdb_id BIGINT UNIQUE,
    name VARCHAR(100) NOT NULL,
    abbreviation VARCHAR(30),
    slug VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE stores (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    slug VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE games (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    igdb_id BIGINT UNIQUE,
    slug VARCHAR(150) NOT NULL UNIQUE,
    title VARCHAR(255) NOT NULL,
    title_normalized VARCHAR(255) NOT NULL,
    summary TEXT,
    release_date DATE,
    kind VARCHAR(20) NOT NULL DEFAULT 'MAIN'
        CHECK (kind IN ('MAIN', 'REMAKE', 'REMASTER', 'EXPANDED', 'EXPANSION', 'STANDALONE', 'PORT')),
    cover_image_id VARCHAR(50),
    metadata JSONB NOT NULL DEFAULT '{}',
    igdb_rating NUMERIC(5, 2),
    igdb_rating_count INTEGER,
    synced_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX games_title_trgm_idx ON games USING gin (title_normalized gin_trgm_ops);
CREATE INDEX games_release_date_idx ON games (release_date);

CREATE TABLE game_genres (
    game_id BIGINT NOT NULL REFERENCES games (id) ON DELETE CASCADE,
    genre_id BIGINT NOT NULL REFERENCES genres (id),
    PRIMARY KEY (game_id, genre_id)
);

CREATE INDEX game_genres_genre_idx ON game_genres (genre_id, game_id);

CREATE TABLE game_platforms (
    game_id BIGINT NOT NULL REFERENCES games (id) ON DELETE CASCADE,
    platform_id BIGINT NOT NULL REFERENCES platforms (id),
    PRIMARY KEY (game_id, platform_id)
);

CREATE INDEX game_platforms_platform_idx ON game_platforms (platform_id, game_id);

INSERT INTO stores (name, slug) VALUES
    ('Steam', 'steam'),
    ('Epic Games Store', 'epic-games-store'),
    ('GOG', 'gog'),
    ('PlayStation Store', 'playstation-store'),
    ('Microsoft Store', 'microsoft-store'),
    ('Nintendo eShop', 'nintendo-eshop'),
    ('Nuuvem', 'nuuvem'),
    ('Amazon', 'amazon'),
    ('Mercado Livre', 'mercado-livre'),
    ('Loja física', 'loja-fisica'),
    ('Outra', 'outra');
