-- As regras completas da RN02 ficam no domínio, com mensagens claras; os CHECKs são a rede de segurança.
CREATE TABLE library_entries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    game_id BIGINT NOT NULL REFERENCES games (id),
    status VARCHAR(10) NOT NULL CHECK (status IN ('WISHLIST', 'BACKLOG', 'PLAYING', 'PLAYED', 'DROPPED')),
    favorite BOOLEAN NOT NULL DEFAULT false,

    rating NUMERIC(3, 2) CHECK (rating BETWEEN 0 AND 5 AND rating * 4 = trunc(rating * 4)),
    recommends BOOLEAN,
    review_text VARCHAR(2000),
    has_spoilers BOOLEAN,
    reviewed_at TIMESTAMPTZ,

    played_platform_id BIGINT REFERENCES platforms (id),
    hours_played INTEGER CHECK (hours_played >= 0),
    started_on DATE,
    finished_on DATE,
    completed BOOLEAN,

    acquisition VARCHAR(12) CHECK (acquisition IN ('PURCHASED', 'GIFT', 'SUBSCRIPTION', 'FREE')),
    store_id BIGINT REFERENCES stores (id),
    price_paid NUMERIC(10, 2) CHECK (price_paid >= 0),
    currency VARCHAR(3) CHECK (currency ~ '^[A-Z]{3}$'),
    acquired_on DATE,

    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),

    UNIQUE (user_id, game_id),
    CHECK (price_paid IS NULL OR (currency IS NOT NULL AND acquisition = 'PURCHASED')),
    CHECK (finished_on IS NULL OR started_on IS NULL OR finished_on >= started_on),
    CHECK (favorite = false OR status IN ('PLAYING', 'PLAYED')),
    CHECK (status IN ('PLAYING', 'PLAYED', 'DROPPED') OR (rating IS NULL AND review_text IS NULL AND recommends IS NULL))
);

CREATE INDEX library_entries_user_status_idx ON library_entries (user_id, status, updated_at DESC);
CREATE INDEX library_entries_game_idx ON library_entries (game_id);
CREATE INDEX library_entries_reviews_idx ON library_entries (game_id, reviewed_at DESC) WHERE review_text IS NOT NULL;
