-- Feed (RF51): o que cada pessoa fez na biblioteca. Quem segue quem fica em follows; o feed junta os dois na leitura.
CREATE TABLE activities (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    type VARCHAR(10) NOT NULL CHECK (type IN ('STATUS', 'REVIEW', 'FAVORITE')),
    game_id BIGINT NOT NULL REFERENCES games (id),
    -- Tirar o jogo da biblioteca apaga as atividades dele (RN16).
    entry_id BIGINT NOT NULL REFERENCES library_entries (id) ON DELETE CASCADE,
    -- STATUS guarda o status daquele momento, como {"status": "PLAYED", "completed": true}.
    data JSONB NOT NULL DEFAULT '{}',
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX activities_user_idx ON activities (user_id, created_at DESC);
CREATE INDEX activities_entry_idx ON activities (entry_id);

-- As entradas que já existiam entram no feed com o status atual, na data da última mudança, e com a avaliação, na
-- data dela.
INSERT INTO activities (user_id, type, game_id, entry_id, data, created_at)
SELECT user_id, 'STATUS', game_id, id, jsonb_build_object('status', status, 'completed', coalesce(completed, false)),
       updated_at
FROM library_entries;

INSERT INTO activities (user_id, type, game_id, entry_id, created_at)
SELECT user_id, 'REVIEW', game_id, id, reviewed_at
FROM library_entries
WHERE (rating IS NOT NULL OR review_text IS NOT NULL) AND reviewed_at IS NOT NULL;
