-- Denúncias de avaliações (RF53). A moderação resolve de uma vez todas as abertas de uma avaliação.
CREATE TABLE reports (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reporter_id BIGINT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    entry_id BIGINT NOT NULL REFERENCES library_entries (id) ON DELETE CASCADE,
    reason VARCHAR(10) NOT NULL CHECK (reason IN ('SPAM', 'OFFENSIVE', 'SPOILER', 'OTHER')),
    details VARCHAR(500),
    status VARCHAR(8) NOT NULL DEFAULT 'OPEN' CHECK (status IN ('OPEN', 'KEPT', 'REMOVED')),
    resolved_by BIGINT REFERENCES users (id) ON DELETE SET NULL,
    resolved_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Uma denúncia aberta por pessoa e avaliação (RN18); depois de resolvida, dá para denunciar de novo.
CREATE UNIQUE INDEX reports_open_unique ON reports (reporter_id, entry_id) WHERE status = 'OPEN';
CREATE INDEX reports_entry_idx ON reports (entry_id);
